# Generated by Django 3.2 on 2021-07-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temporarystorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_at', models.DateTimeField(auto_created=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
