# Generated by Django 3.2 on 2021-07-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarystorage',
            name='send_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
