# Generated by Django 3.2 on 2021-07-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0002_alter_temporarystorage_send_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarystorage',
            name='send_at',
            field=models.DateTimeField(),
        ),
    ]
