# Generated by Django 3.2 on 2021-05-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpublicdata',
            name='code',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
